# Generated by Django 4.0.6 on 2022-07-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.TextField(verbose_name='Position')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
            ],
        ),
    ]
