# Generated by Django 4.0.6 on 2022-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idType', models.IntegerField(verbose_name='Id')),
                ('typeName', models.CharField(max_length=20, verbose_name='Type of product')),
            ],
        ),
    ]
