# Generated by Django 4.0.6 on 2022-09-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ImgURL',
        ),
    ]
